# Generated by Django 4.0 on 2022-01-22 08:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('places', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=200)),
                ('age_restriction', models.BooleanField(default=False)),
                ('confirmed_reservations', models.SmallIntegerField(default=0)),
                ('no_of_reservations', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scr', models.ImageField(upload_to='images/event_logo/', verbose_name='Logo/Image')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='event_booker.event')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('birth_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1872), django.core.validators.MaxValueValidator(2022)])),
                ('is_checked', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('invited', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.UUID('d29d91fa-99ff-4d47-b5cb-96b3b9551bb5'))),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event_booker.event')),
            ],
        ),
    ]
