# Generated by Django 4.0 on 2021-12-25 10:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('places', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('age_restriction', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scr', models.ImageField(upload_to='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event_booker.event')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('berth_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2021)])),
                ('is_checked', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('invited', models.BooleanField(default=False)),
                ('uuid', models.UUIDField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event_booker.event')),
            ],
        ),
    ]
