# Generated by Django 4.0 on 2021-12-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='confirmed_reservations',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='no_of_reservations',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='age_restriction',
            field=models.BooleanField(default=False),
        ),
    ]
