# Generated by Django 4.0 on 2022-01-02 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booker', '0002_event_confirmed_reservations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='berth_year',
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_year',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2022)]),
            preserve_default=False,
        ),
    ]
