# Generated by Django 4.0 on 2022-01-07 11:36

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event_booker', '0003_remove_customer_berth_year_customer_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2022)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0c00f371-a334-4b26-ab39-f20fa4a18377')),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
