# Generated by Django 4.0 on 2022-01-13 09:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event_booker', '0004_alter_customer_birth_year_alter_customer_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1872), django.core.validators.MaxValueValidator(2022)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fcfced99-4ef6-4fae-adbf-2f5df848c230')),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='event_booker.event'),
        ),
    ]
